apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.data.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.persistence.data.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ .Values.persistence.data.storageClassName }}
  accessModes:
{{- toYaml .Values.persistence.data.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.storageSize }}
