{{- if and (ne .Values.persistence.backups.backupType "objectStorage") (ne .Values.persistence.backups.backupType "volumeStorage") -}}
{{- fail (printf "Invalid persistence.backups.backupType=%q. Allowed values: objectStorage, volumeStorage." .Values.persistence.backups.backupType) -}}
{{- end -}}
### OBJECT STORAGE PV ###
{{- if eq .Values.persistence.backups.backupType "objectStorage" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.backups.name }}
  {{- with .Values.persistence.backups.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
{{- toYaml .Values.persistence.backups.objectStorage.accessModes | nindent 4 }}
  capacity:
    storage: {{ .Values.persistence.backups.objectStorage.size }}
  csi:
    driver: {{ .Values.persistence.backups.objectStorage.csiDriver }}
    fsType: {{ .Values.persistence.backups.objectStorage.fsType }}
    volumeHandle: {{ .Values.persistence.backups.objectStorage.bucketId }}
    {{- with .Values.persistence.backups.objectStorage.volumeAttributes }}
    volumeAttributes:
{{- toYaml . | nindent 6 }}
    {{- end }}
    nodePublishSecretRef:
      name: {{ .Values.persistence.backups.objectStorage.accessKeySecretKeySecretName }}
      namespace: {{ .Release.Namespace }}
  persistentVolumeReclaimPolicy: {{ .Values.persistence.backups.objectStorage.persistentVolumeReclaimPolicy }}
  storageClassName: {{ .Values.persistence.backups.objectStorage.storageClassName }}
  {{- with .Values.persistence.backups.objectStorage.mountOptions }}
  mountOptions:
{{- toYaml . | nindent 4 }}
  {{- end }}
---
### OBJECT STORAGE PVC ###
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.backups.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.persistence.backups.objectStorage.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  volumeName: {{ .Values.persistence.backups.name }}
  storageClassName: {{ .Values.persistence.backups.objectStorage.storageClassName }}
  accessModes:
{{- toYaml .Values.persistence.backups.objectStorage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.backups.objectStorage.size }}
### VOLUME STORAGE PVC ###
{{- else if eq .Values.persistence.backups.backupType "volumeStorage" }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.backups.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.persistence.backups.volumeStorage.annotations }}
  annotations:
{{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  storageClassName: {{ .Values.persistence.backups.volumeStorage.storageClassName }}
  accessModes:
{{- toYaml .Values.persistence.backups.volumeStorage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.backups.volumeStorage.storageSize }}
{{- end }}
