apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.logs.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    everest.io/disk-volume-type: {{ .Values.persistence.logs.storageType }}
    {{- with .Values.persistence.logs.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  storageClassName: {{ .Values.persistence.logs.storageClassName }}
  accessModes: {{ .Values.persistence.logs.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.storageSize }}
