{{- if .Values.persistence.temp.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.temp.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    everest.io/disk-volume-type: {{ .Values.persistence.temp.storageType }}
spec:
  storageClassName: {{ .Values.persistence.temp.storageClassName }}
  accessModes: {{ .Values.persistence.temp.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.temp.storageSize }}
  {{- end }}