{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.route.name | default .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $value := .Values.route.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  host: {{ .Values.config.baseUrl | trimPrefix "https://" | trimPrefix "http://" }}
  to:
    kind: Service
    name: {{ .Values.service.name }}
    weight: 100
  port:
    targetPort: {{ .Values.service.port }}
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination | default "edge" }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecurePolicy | default "Redirect" }}
  {{- end }}
{{- end }}
