apiVersion: v2
name: espocrm
description: A Helm chart for deploying EspoCRM on Kubernetes
type: application
icon: https://raw.githubusercontent.com/TWENTY-20/helm-charts/main/espocrm/icon.png
version: 1.2.5
appVersion: "9.2.4"

home: https://www.espocrm.com

sources:
  - https://github.com/TWENTY-20/helm-charts/tree/main/espocrm

keywords:
  - espocrm
  - espo
  - crm
  - helm
  - kubernetes

maintainers:
  - name: twenty20
    email: it-factory@twenty20.de
    url: https://twenty20.de