{{- if and .Values.nginx.ingress.enabled .Values.nginx.traefik.enabled }}
{{- fail "You cannot enable both nginx.ingress and nginx.traefik. Please choose only one." }}
{{- end }}
{{- if and .Values.nginx.ingress.enabled (not .Values.nginx.traefik.enabled) }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Values.nginx.ingress.name }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.nginx.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.nginx.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  rules:
    {{- range .Values.nginx.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ $.Values.service.name }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
  {{- if .Values.nginx.ingress.tls }}
  tls:
    {{- range .Values.nginx.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
{{- end }}